### ISSUE TITLE
Не хватает места для нормального использования

### ISSUE THREAD

**Issue by AliensWithdrawPeople** [caenHV/environment#2]
Даже после всех процедур, что ты описал в гайде, на моменте установки пакета Setup выдаётся следущая штука:
`ERROR: Could not install packages due to an OSError: [Errno 28] No space left on device: '/usr/local/lib/python3.12/dist-packages/SQLAlchemy-2.0.23.dist-info/INSTALLERmvir1oga.tmp'`
Нужно разобраться, как перекинуть папку с кэшем куда-нибудь.

Из-за этого не все тесты смог провести. Но удалось  напряжение поднять и поопрашивать сетап (позже гляну записанное; Может там хрень). Предварительно можно сказать, что Handler рабочий. Допишу тикеты и их почекаю в следующий раз.

**Comment by nikita-p** [comment]
Перенёс кэш докера на `/store11` (там где-то 600 ГБ свободно) согласно [инструкции](https://www.digitalocean.com/community/questions/how-to-move-the-default-var-lib-docker-to-another-directory-for-docker-on-linux?comment=168943) (комментарий от mwrochna)
