### ISSUE TITLE
Нужно примонтировать папку для работы с ODB

### ISSUE THREAD

**Issue by AliensWithdrawPeople** [caenHV/environment#4]
https://github.com/caenHV/environment/blob/ae2a57e95a7427f3d0d6fa2555c4eef07cebdc6d/dq11/compose.yaml#L34C1-L35C23

В версии, которая сейчас на dq11 я изменил конфиг и compose:
В compose для монитора добавил volumes: - /home/cmd3daq/caendc/data/ : /odb/data
В конфиге поменял соответсвующее имя файла  param_file_path на /odb/data/last_measurement.json

Если это не протеворечит никаким принципам, то я и здесь это поменяю.

@nikita-p

**Comment by nikita-p** [comment]
да, конечно, меняй
